### ISSUE TITLE
AttributeError: 'MyConfig' object has no attribute 'epoch1'

### ISSUE THREAD

**Issue by SeekPoint** [Chao-Lu/Bi-RCNN#4]
ub16hp@UB16HP:~/ub16_prj/Bi-RCNN$ python3 bircnn.py
Traceback (most recent call last):
  File "bircnn.py", line 438, in <module>
    train(model_index=1)
  File "bircnn.py", line 296, in train
    config.epochs = config.epoch1
AttributeError: 'MyConfig' object has no attribute 'epoch1'
ub16hp@UB16HP:~/ub16_prj/Bi-RCNN$

**Comment by Jerryten** [comment]
I also meet this problem

**Comment by echo-mo** [comment]
So is there anybody already find out how to solve this problem above?
